title: Robin Familara
description: Unlimited interesting things.
author: Robin Familara
email: rfamilara2019@gmail.com
phone: (504) 210-7342
github: https://github.com/ironbott-tech
about: I am a Software Engineer at <a href="https://www.lambdaschool.com" target="_blank">Build.com</a> and a freelance developer. I love working on backend and frontend technologies.
disqus_shortname: hybrid-engineer
google_analytics: 
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/cybertechbin"
    - icon: fa-twitter
      link: "https://twitter.com/Niborhoods"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/rf2017/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/ironBott-tech"

share:
  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://github.com/ironBott-tech/ironBott-tech.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
